Set LOCAL_DIRECTORY in .env file instead of scripts.

diff --git a/nix/bootstrap/build b/nix/bootstrap/build
--- a/nix/bootstrap/build
+++ b/nix/bootstrap/build
@@ -52,12 +52,20 @@ if [ -z $HOME_NIX ]; then
   exit 2
 fi
 
+if [ -z $LOCAL_DIRECTORY ]; then
+  echo "ERROR: Environment variable LOCAL_DIRECTORY does not have a value."
+  echo "Review .env.README for .env file format."
+  exit 2
+fi
+
 if [ ! -f ./.env ]; then
   cp -p $HOME/.env.boot-dev ./.env
 fi
 
-export LOCAL_DIRECTORY="$HOME/container-host"
-mkdir -p $LOCAL_DIRECTORY
+export LOCAL_DIRECTORY
+if [ ! -f $LOCAL_DIRECTORY ]; then
+  mkdir -p $LOCAL_DIRECTORY
+fi
 
 DOCKER_COMPOSE=$(which docker-compose)
 PODMAN=$(which podman)
