Added check for local .env and /home/jcroft/.env.boot-dev environment files.

diff --git a/nix/bootstrap/build b/nix/bootstrap/build
--- a/nix/bootstrap/build
+++ b/nix/bootstrap/build
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+if [ -z "./.env" ];
+then
+  . ./.env
+elif [ -z "~/.env.boot-dev" ];
+then
+  . ~/.env.boot-dev
+else
+  echo "ERROR: No .env file exists."
+  exit 1
+fi
+
 export LOCAL_DIRECTORY="$HOME/container-host"
 mkdir -p $LOCAL_DIRECTORY
 
